version: '3'
services:
  elasticsearch:
    image: elasticsearch:5
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.6
  redis:
    image: redis
    volumes:
      - redis:/data
  web:
    build: .
    command: bin/docker-start
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    links:
      - postgres
      - elasticsearch
      - redis
      - rabbitmq
    volumes:
      - .:/bugs_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - rabbitmq
volumes:
  elasticsearch: {}
  postgres: {}
  redis: {}
  
