version: '3'
services:
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    volumes:
      - redis:/data
  web:
    build: .
    command: bin/docker-start
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_PASSWORD=
      - POSTGRESQL_USERNAME=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    links:
      - postgres
      - elasticsearch
      - redis
      - rabbitmq
    volumes:
      - .:/bugs_app
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - rabbitmq
volumes:
  elasticsearch: {}
  postgres: {}
  redis: {}
